# Site settings
title: Opendi Internationl AG
email: info@opendi.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.opendi.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
